<?php
// Delete  social  login if exists
$db->Execute('DELETE FROM '. TABLE_CONFIGURATION . ' WHERE configuration_key IN("SOCIAL_LOGIN",
	"FACEBOOK_OPEN_GRAPH_APPID", 
	"FACEBOOK_OPEN_GRAPH_APPSECRET",
	"FACEBOOK_CALL_BACK_URL",
	"GOOGLE_APPID",
	"GOOGLE_CALL_BACK_URL",
	"GOOGLE_APPSECRET", 
	"GOOGLE_APP_NAME")');