<?php
$legacyKeys = [
    'MODULE_PAYMENT_BRAINTREE_PAYPAL_CLIENT_ID_SANDBOX',
    'MODULE_PAYMENT_BRAINTREE_PAYPAL_CLIENT_SECRET_SANDBOX',
    'MODULE_PAYMENT_BRAINTREE_PAYPAL_CLIENT_ID_PRODUCTION',
    'MODULE_PAYMENT_BRAINTREE_PAYPAL_CLIENT_SECRET_PRODUCTION',
];

foreach ($legacyKeys as $key) {
    $db->Execute(
        "DELETE FROM " . TABLE_CONFIGURATION . " WHERE configuration_key = '" . zen_db_input($key) . "'"
    );
}
