<?php
/**
 * Recurring-subscription observer for PayPal Advanced Checkout.
 *
 * Detects subscription-ready products during order creation and logs them so
 * follow-up billing can reference the vaulted card profile captured at checkout.
 *
 * @copyright Copyright 2025 Zen Cart Development Team
 * @license   https://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 */

use PayPalAdvancedCheckout\Common\Logger;
use PayPalAdvancedCheckout\Common\SubscriptionManager;
use PayPalAdvancedCheckout\Common\VaultManager;
use Zencart\Traits\ObserverManager;

require_once DIR_FS_CATALOG . DIR_WS_MODULES . 'payment/paypal/ppacAutoload.php';
if (!trait_exists('Zencart\\Traits\\ObserverManager')) {
    require_once DIR_FS_CATALOG . DIR_WS_MODULES . 'payment/paypal/PayPalAdvancedCheckout/Compatibility/ObserverManager.php';
}
$paypalacSubscriptionHelper = DIR_FS_CATALOG . 'includes/functions/extra_functions/paypalac_subscription_functions.php';
if (is_file($paypalacSubscriptionHelper)) {
    require_once $paypalacSubscriptionHelper;
}
class zcObserverPaypaladvcheckoutRecurring
{
    use ObserverManager;

    /** @var array<int,bool> */
    protected array $processedOrders = [];

    /** @var Logger */
    protected Logger $log;

    /**
     * Normalized attribute keys mapped to the values this observer understands.
     */
    protected const ATTRIBUTE_KEY_MAP = [
        'plan_id' => ['paypal_subscription_plan_id'],
        'billing_period' => ['paypal_subscription_billing_period', 'billing_period', 'billingperiod'],
        'billing_frequency' => ['paypal_subscription_billing_frequency', 'billing_frequency', 'billingfrequency'],
        'total_billing_cycles' => ['paypal_subscription_total_billing_cycles', 'total_billing_cycles', 'totalbillingcycles'],
        'trial_period' => ['paypal_subscription_trial_period'],
        'trial_frequency' => ['paypal_subscription_trial_frequency'],
        'trial_total_cycles' => ['paypal_subscription_trial_total_cycles'],
        'setup_fee' => ['paypal_subscription_setup_fee'],
    ];

    protected const PERIOD_MAP = [
        'DAY' => 'DAY',
        'DAYS' => 'DAY',
        'DAILY' => 'DAY',
        'WEEK' => 'WEEK',
        'WEEKS' => 'WEEK',
        'WEEKLY' => 'WEEK',
        'MONTH' => 'MONTH',
        'MONTHS' => 'MONTH',
        'MONTHLY' => 'MONTH',
        'YEAR' => 'YEAR',
        'YEARS' => 'YEAR',
        'YEARLY' => 'YEAR',
        'SEMI-MONTH' => 'SEMI_MONTH',
        'SEMI_MONTH' => 'SEMI_MONTH',
        'SEMIMONTH' => 'SEMI_MONTH',
        'SEMI-MONTHLY' => 'SEMI_MONTH',
    ];

    public function __construct()
    {
        // -----
        // If the base paypalac payment-module isn't installed, nothing further to do here.
        // The observer is needed as long as any PayPal payment module is enabled.
        //
        if (!defined('MODULE_PAYMENT_PAYPALAC_VERSION')) {
            return;
        }

        // -----
        // Check if at least one PayPal payment module is enabled
        //
        $anyModuleEnabled = (
            (defined('MODULE_PAYMENT_PAYPALAC_STATUS') && MODULE_PAYMENT_PAYPALAC_STATUS === 'True') ||
            (defined('MODULE_PAYMENT_PAYPALAC_CREDITCARD_STATUS') && MODULE_PAYMENT_PAYPALAC_CREDITCARD_STATUS === 'True') ||
            (defined('MODULE_PAYMENT_PAYPALAC_APPLEPAY_STATUS') && MODULE_PAYMENT_PAYPALAC_APPLEPAY_STATUS === 'True') ||
            (defined('MODULE_PAYMENT_PAYPALAC_GOOGLEPAY_STATUS') && MODULE_PAYMENT_PAYPALAC_GOOGLEPAY_STATUS === 'True') ||
            (defined('MODULE_PAYMENT_PAYPALAC_VENMO_STATUS') && MODULE_PAYMENT_PAYPALAC_VENMO_STATUS === 'True') ||
            (defined('MODULE_PAYMENT_PAYPALAC_SAVEDCARD_STATUS') && MODULE_PAYMENT_PAYPALAC_SAVEDCARD_STATUS === 'True')
        );

        if (!$anyModuleEnabled) {
            return;
        }

        // Initialize logger only if we're actually going to attach to notifications
        $this->log = new Logger('recurring-observer');
        $this->log->write('PayPalAdvancedCheckout Recurring Observer: Initialized and attached to notifications.');
        
        $this->attach($this, [
            'NOTIFY_CHECKOUT_PROCESS_AFTER_ORDER_CREATE_ADD_PRODUCTS',
            'NOTIFY_PAYPALAC_VAULT_CARD_SAVED',
            'NOTIFY_PAYPALAC_AUTHORIZATION_FULLY_CAPTURED',
        ]);
    }

    public function updateNotifyCheckoutProcessAfterOrderCreateAddProducts(&$class, $eventID, $params): void
    {
        $ordersId = (int)($_SESSION['order_number_created'] ?? 0);
        
        $this->log->write("==> Subscription Observer: NOTIFY_CHECKOUT_PROCESS_AFTER_ORDER_CREATE_ADD_PRODUCTS fired.");
        $this->log->write("    Order ID: " . ($ordersId > 0 ? $ordersId : 'NOT SET'));
        
        // Skip subscription creation for orders generated by the cron (recurring payments)
        // These orders are renewals of existing subscriptions and should not create new ones
        if (!empty($_SESSION['in_cron']) || !empty($_SESSION['automatic_subscription_order'])) {
            $this->log->write("    Skipping: Order is a recurring payment from cron/automatic subscription.");
            return;
        }
        
        if ($ordersId <= 0 || isset($this->processedOrders[$ordersId])) {
            if ($ordersId <= 0) {
                $this->log->write("    Skipping: Order ID is not set or invalid.");
            } else {
                $this->log->write("    Skipping: Order #$ordersId already processed.");
            }
            return;
        }

        if (function_exists('paypalac_materialize_accept_automatic_renewal_order_attributes')) {
            paypalac_materialize_accept_automatic_renewal_order_attributes($ordersId);
        }

        $this->processedOrders[$ordersId] = true;

        global $db, $zco_notifier;

        // PayPal-managed subscription branch: when paypalac::createPayPalSubscription
        // ran during pre_confirmation_check and the customer approved at PayPal, the
        // session carries the PayPal subscription remote id (I-XXXXXX) plus the
        // resolved subscription_product config. Persist a paypal_subscriptions row
        // tagged with paypal_subscription_remote_id and skip the Zen Cart-managed
        // (saved_credit_cards_recurring) path: PayPal owns the billing schedule
        // from here on, BILLING.SUBSCRIPTION.ACTIVATED will flip the order paid,
        // and PAYMENT.SALE.COMPLETED reports each recurring payment via webhook.
        if (!empty($_SESSION['PayPalAdvancedCheckout']['Subscription']['confirmed'])) {
            $this->logPayPalManagedSubscription($ordersId);
            unset($_SESSION['PayPalAdvancedCheckout']['Subscription']);
            return;
        }

        $orderInfo = $db->Execute(
            "SELECT customers_id, currency, currency_value,
                    billing_name, billing_company,
                    billing_street_address, billing_suburb, billing_city,
                    billing_state, billing_postcode, billing_country,
                    delivery_country
               FROM " . TABLE_ORDERS . "
              WHERE orders_id = " . $ordersId . "
              LIMIT 1"
        );

        if ($orderInfo->EOF) {
            $this->log->write("    ERROR: Order #$ordersId not found in database.");
            return;
        }

        $customersId = (int)$orderInfo->fields['customers_id'];
        $currency = (string)($orderInfo->fields['currency'] ?? (defined('DEFAULT_CURRENCY') ? DEFAULT_CURRENCY : ''));
        $currencyValue = (float)($orderInfo->fields['currency_value'] ?? 1.0);
        
        // Extract billing address from order for subscription storage
        $billingAddress = array(
            'billing_name' => (string)($orderInfo->fields['billing_name'] ?? ''),
            'billing_company' => (string)($orderInfo->fields['billing_company'] ?? ''),
            'billing_street_address' => (string)($orderInfo->fields['billing_street_address'] ?? ''),
            'billing_suburb' => (string)($orderInfo->fields['billing_suburb'] ?? ''),
            'billing_city' => (string)($orderInfo->fields['billing_city'] ?? ''),
            'billing_state' => (string)($orderInfo->fields['billing_state'] ?? ''),
            'billing_postcode' => (string)($orderInfo->fields['billing_postcode'] ?? ''),
            'billing_country' => (string)($orderInfo->fields['billing_country'] ?? ''),
        );
        
        // Get billing country ID and ISO code
        if (!empty($billingAddress['billing_country'])) {
            $countryQuery = $db->Execute(
                "SELECT countries_id, countries_iso_code_2
                   FROM " . TABLE_COUNTRIES . "
                  WHERE countries_name = '" . zen_db_input($billingAddress['billing_country']) . "'
                  LIMIT 1"
            );
            if (!$countryQuery->EOF) {
                $billingAddress['billing_country_id'] = (int)$countryQuery->fields['countries_id'];
                $billingAddress['billing_country_code'] = (string)$countryQuery->fields['countries_iso_code_2'];
            }
        }
        
        $this->log->write("    Customer ID: $customersId, Currency: $currency, Currency Value: $currencyValue");
        $this->log->write("    Billing Address: " . Logger::logJSON($billingAddress));
        
        // Extract shipping information from order totals
        $shippingInfo = array(
            'shipping_method' => '',
            'shipping_cost' => null
        );
        
        // Get shipping method and cost from orders_total
        $shippingQuery = $db->Execute(
            "SELECT class, title, value
               FROM " . TABLE_ORDERS_TOTAL . "
              WHERE orders_id = " . $ordersId . "
                AND class = 'ot_shipping'
              LIMIT 1"
        );
        
        if (!$shippingQuery->EOF) {
            $shippingInfo['shipping_method'] = (string)$shippingQuery->fields['title'];
            $shippingInfo['shipping_cost'] = (float)$shippingQuery->fields['value'];
            $this->log->write("    Shipping: " . Logger::logJSON($shippingInfo));
        } else {
            $this->log->write("    Shipping: No shipping charge found (may be free or digital product)");
        }

        $products = $db->Execute(
            "SELECT orders_products_id, products_id, products_name, products_quantity, final_price
               FROM " . TABLE_ORDERS_PRODUCTS . "
              WHERE orders_id = " . $ordersId
        );

        if ($products->EOF) {
            $this->log->write("    No products found in order #$ordersId.");
            return;
        }

        // init_observers loads this class before auto.paypaladvcheckout_vault.php (alphabetical order),
        // so session VaultCardData may not be in paypal_vault yet when this handler runs.
        $this->ensureSessionVaultPersistedForOrder($ordersId, $customersId);

        $vaultRecord = $this->findVaultRecord($customersId, $ordersId);
        $loggedAny = false;
        
        if ($vaultRecord !== null) {
            $this->log->write("    Vault record found: " . Logger::logJSON($vaultRecord));
            // Sync vault to saved_credit_cards table BEFORE attempting subscription creation
            // This ensures saved_credit_card_id is available for Zen Cart-managed subscriptions
            $this->syncVaultToSavedCreditCards($vaultRecord);
        } else {
            $this->log->write("    No vault record found for customer #$customersId / order #$ordersId.");
        }

        while (!$products->EOF) {
            $ordersProductsId = (int)$products->fields['orders_products_id'];
            $this->log->write("    Checking product #$ordersProductsId: " . $products->fields['products_name']);
            
            $attributeMap = $this->getAttributeMap($ordersProductsId);
            $this->log->write("    Product attributes: " . Logger::logJSON($attributeMap));
            
            $subscriptionAttributes = $this->extractSubscriptionAttributes($attributeMap);
            if ($subscriptionAttributes === null) {
                $this->log->write("    Product #$ordersProductsId: No valid subscription attributes found, skipping.");
                $products->MoveNext();
                continue;
            }
            
            $this->log->write("    Product #$ordersProductsId: Valid subscription attributes extracted: " . Logger::logJSON($subscriptionAttributes));

            // Two subscription creation paths are supported:
            //   - PayPal-managed subscriptions: products that carry a
            //     paypal_subscription_plan_id attribute. These are written to
            //     TABLE_PAYPAL_SUBSCRIPTIONS and PayPal owns the billing schedule.
            //   - Zen Cart-managed (legacy saved-card) subscriptions: products that
            //     carry the three Zen Cart subscription attributes (Billing Period,
            //     Billing Frequency, Total Billing Cycles) but no plan_id. These
            //     are written to TABLE_SAVED_CREDIT_CARDS_RECURRING via
            //     paypalacSavedCardRecurring::schedule_payment() and the cron
            //     captures recurring payments using the customer's saved card.
            $hasPlanId = !empty($subscriptionAttributes['plan_id']);

            if (!$hasPlanId) {
                $created = $this->createZenCartManagedSubscription(
                    $customersId,
                    $ordersId,
                    $ordersProductsId,
                    [
                        'products_id' => (int)$products->fields['products_id'],
                        'products_name' => (string)$products->fields['products_name'],
                        'final_price' => (float)$products->fields['final_price'],
                    ],
                    $subscriptionAttributes,
                    $attributeMap,
                    $vaultRecord,
                    $currency,
                    $billingAddress,
                    $shippingInfo
                );
                if ($created === true) {
                    $loggedAny = true;
                }
                $products->MoveNext();
                continue;
            }

            // PayPal-managed subscription (has plan_id) -> Save to paypal_subscriptions table
            $this->log->write("    Product #$ordersProductsId: PayPal-managed subscription (has plan_id), routing to paypal_subscriptions.");

            $paypalVaultId = 0;
            $vaultId = '';
            if ($vaultRecord !== null) {
                $paypalVaultId = (int)($vaultRecord['paypal_vault_id'] ?? 0);
                $vaultId = (string)($vaultRecord['vault_id'] ?? '');
            }

            $authorizeIntentCatalog = $this->paypalacCheckoutUsesAuthorizeIntent();
            if ($vaultRecord === null) {
                $status = SubscriptionManager::STATUS_AWAITING_VAULT;
                $this->log->write("    No vault record, status: AWAITING_VAULT");
            } elseif ($vaultId !== '' && $paypalVaultId > 0) {
                $status = SubscriptionManager::STATUS_ACTIVE;
                $this->log->write("    Vault complete (paypal_vault_id=$paypalVaultId, vault_id=$vaultId), status: ACTIVE");
            } elseif ($authorizeIntentCatalog) {
                // Authorize-only checkout: order funds are not captured yet, but the subscription
                // should still be treated as active in admin. Recurring runs use AUTHORIZE intent
                // so staff capture settlements manually.
                $status = SubscriptionManager::STATUS_ACTIVE;
                $this->log->write("    Authorize-only checkout: subscription status ACTIVE for order #$ordersId (vault row present; paypal_vault_id=$paypalVaultId, vault_id len=" . strlen($vaultId) . ').');
            } else {
                $status = SubscriptionManager::STATUS_AWAITING_VAULT;
                $this->log->write("    Vault incomplete (paypal_vault_id=$paypalVaultId, vault_id=$vaultId), status: AWAITING_VAULT");
            }

            $subscriptionId = SubscriptionManager::logSubscription([
                'customers_id' => $customersId,
                'orders_id' => $ordersId,
                'orders_products_id' => $ordersProductsId,
                'products_id' => (int)$products->fields['products_id'],
                'products_name' => (string)$products->fields['products_name'],
                'products_quantity' => (float)$products->fields['products_quantity'],
                'plan_id' => $subscriptionAttributes['plan_id'],
                'billing_period' => $subscriptionAttributes['billing_period'],
                'billing_frequency' => $subscriptionAttributes['billing_frequency'],
                'total_billing_cycles' => $subscriptionAttributes['total_billing_cycles'],
                'trial_period' => $subscriptionAttributes['trial_period'],
                'trial_frequency' => $subscriptionAttributes['trial_frequency'],
                'trial_total_cycles' => $subscriptionAttributes['trial_total_cycles'],
                'setup_fee' => $subscriptionAttributes['setup_fee'],
                'amount' => (float)$products->fields['final_price'],
                'currency_code' => $currency,
                'currency_value' => $currencyValue,
                'paypal_vault_id' => $paypalVaultId,
                'vault_id' => $vaultId,
                'status' => $status,
                'attributes' => $attributeMap,
            ]);

            if ($subscriptionId > 0) {
                $loggedAny = true;
                $this->log->write("    SUCCESS: Vaulted subscription #$subscriptionId created for product #$ordersProductsId.");
            } else {
                $this->log->write("    ERROR: Failed to create vaulted subscription for product #$ordersProductsId.");
            }

            $products->MoveNext();
        }

        if ($loggedAny) {
            $this->log->write("    Subscription(s) created successfully, triggering NOTIFY_RECURRING_ORDER_LOGGED.");
            $zco_notifier->notify('NOTIFY_RECURRING_ORDER_LOGGED', [
                'orders_id' => $ordersId,
            ]);
        } else {
            $this->log->write("    No subscriptions were created for order #$ordersId.");
        }
    }

    /**
     * Handle vault card save notification to activate subscriptions that were awaiting vault.
     *
     * When a vault card is saved (either immediately after order or later via webhook),
     * this method finds any subscriptions for the same customer/order that are in
     * 'awaiting_vault' status and activates them by linking them to the vault.
     *
     * @param object $class The calling class
     * @param string $eventID The event identifier
     * @param array $vaultRecord The saved vault record from VaultManager
     */
    public function updateNotifyPaypalacVaultCardSaved(&$class, $eventID, $vaultRecord): void
    {
        $this->log->write("==> Subscription Observer: NOTIFY_PAYPALAC_VAULT_CARD_SAVED fired.");
        
        if (!is_array($vaultRecord) || empty($vaultRecord)) {
            $this->log->write("    ERROR: Vault record is empty or invalid.");
            return;
        }
        
        $this->log->write("    Vault record received: " . Logger::logJSON($vaultRecord));

        $customersId = (int)($vaultRecord['customers_id'] ?? 0);
        $ordersId = (int)($vaultRecord['orders_id'] ?? 0);
        $paypalVaultId = (int)($vaultRecord['paypal_vault_id'] ?? 0);
        $vaultId = (string)($vaultRecord['vault_id'] ?? '');

        if ($customersId <= 0 || $ordersId <= 0 || $paypalVaultId <= 0 || $vaultId === '') {
            $this->log->write("    ERROR: Incomplete vault record data (customers_id=$customersId, orders_id=$ordersId, paypal_vault_id=$paypalVaultId, vault_id=$vaultId).");
            return;
        }

        // Activate any subscriptions that were awaiting this vault
        $activatedCount = SubscriptionManager::activateSubscriptionsWithVault(
            $customersId,
            $ordersId,
            $paypalVaultId,
            $vaultId
        );
        
        $this->log->write("    Activated $activatedCount subscription(s) with vault (customer #$customersId, order #$ordersId).");

        if ($activatedCount > 0) {
            global $zco_notifier;
            $zco_notifier->notify('NOTIFY_SUBSCRIPTIONS_ACTIVATED', [
                'customers_id' => $customersId,
                'orders_id' => $ordersId,
                'vault_id' => $vaultId,
                'activated_count' => $activatedCount,
            ]);
            $this->log->write("    NOTIFY_SUBSCRIPTIONS_ACTIVATED notification sent.");
        }

        // Sync vault record to saved_credit_cards table for Zen Cart-managed subscriptions
        $this->syncVaultToSavedCreditCards($vaultRecord);
    }

    /**
     * @return array<string,string>
     */
    protected function getAttributeMap(int $ordersProductsId): array
    {
        global $db;

        $attributes = [];
        $result = $db->Execute(
            "SELECT products_options, products_options_values
               FROM " . TABLE_ORDERS_PRODUCTS_ATTRIBUTES . "
              WHERE orders_products_id = " . $ordersProductsId
        );

        while (!$result->EOF) {
            $key = $this->normalizeAttributeKey((string)$result->fields['products_options']);
            $attributes[$key] = trim((string)$result->fields['products_options_values']);
            $result->MoveNext();
        }

        return $attributes;
    }

    /**
     * @param array<string,string> $attributeMap
     * @return array<string,mixed>|null
     */
    protected function extractSubscriptionAttributes(array $attributeMap): ?array
    {
        if (!$this->attributeMapHasAcceptedAutomaticRenewal($attributeMap)) {
            return null;
        }

        $normalized = [];
        foreach (self::ATTRIBUTE_KEY_MAP as $field => $keys) {
            foreach ($keys as $key) {
                if (isset($attributeMap[$key])) {
                    $normalized[$field] = $attributeMap[$key];
                    break;
                }
            }
        }

        // Either/Or validation logic:
        // IF plan_id is provided -> Only plan_id is required (PayPal-managed subscription)
        // IF plan_id is NOT provided -> billing_period and billing_frequency are required (Zen Cart-managed subscription)
        
        $hasPlanId = !empty($normalized['plan_id']);
        $hasBillingPeriod = !empty($normalized['billing_period']);
        $hasBillingFrequency = !empty($normalized['billing_frequency']);
        
        if ($hasPlanId) {
            // PayPal-managed subscription: plan_id is sufficient
            // Return early with plan_id only (other attributes will be ignored by PayPal)
            return [
                'plan_id' => (string)$normalized['plan_id'],
                'billing_period' => '',
                'billing_frequency' => 0,
                'total_billing_cycles' => 0,
                'trial_period' => '',
                'trial_frequency' => 0,
                'trial_total_cycles' => 0,
                'setup_fee' => 0.0,
                'attributes' => $attributeMap,
            ];
        }
        
        // Zen Cart-managed subscription: billing_period and billing_frequency are required
        if (!$hasBillingPeriod || !$hasBillingFrequency) {
            return null;
        }

        $billingPeriod = $this->normalizePeriod((string)$normalized['billing_period']);
        if ($billingPeriod === null) {
            return null;
        }

        // Numinix and other catalogs often store frequency as a label ("Monthly",
        // "1 Month", "30 Days") rather than a bare integer. Cast-to-int alone
        // turns "Monthly" into 0 and silently drops the subscription.
        $inferredPeriod = null;
        $billingFrequency = $this->parseBillingFrequency(
            (string)$normalized['billing_frequency'],
            $inferredPeriod
        );
        if ($billingFrequency <= 0) {
            return null;
        }
        if ($inferredPeriod !== null && $billingPeriod !== $inferredPeriod) {
            // Prefer the unit embedded in the frequency value when present
            // (e.g. Billing Period=Monthly + Frequency="30 Days").
            $billingPeriod = $inferredPeriod;
        }

        $totalCycles = $this->parseTotalBillingCycles((string)($normalized['total_billing_cycles'] ?? '0'));

        $trialPeriodRaw = (string)($normalized['trial_period'] ?? '');
        $trialPeriod = '';
        if ($trialPeriodRaw !== '') {
            $trialPeriodNormalized = $this->normalizePeriod($trialPeriodRaw, true);
            if ($trialPeriodNormalized === null) {
                $trialPeriod = '';
            } else {
                $trialPeriod = $trialPeriodNormalized;
            }
        }

        $trialFrequency = (int)($normalized['trial_frequency'] ?? 0);
        if ($trialPeriod === '') {
            $trialFrequency = 0;
        }

        $trialTotalCycles = (int)($normalized['trial_total_cycles'] ?? 0);
        if ($trialPeriod === '') {
            $trialTotalCycles = 0;
        }

        $setupFee = $this->parseAmount($normalized['setup_fee'] ?? '');

        return [
            'plan_id' => '',
            'billing_period' => $billingPeriod,
            'billing_frequency' => $billingFrequency,
            'total_billing_cycles' => $totalCycles,
            'trial_period' => $trialPeriod,
            'trial_frequency' => $trialFrequency,
            'trial_total_cycles' => $trialTotalCycles,
            'setup_fee' => $setupFee,
            'attributes' => $attributeMap,
        ];
    }

    protected function normalizePeriod(string $value, bool $allowEmpty = false): ?string
    {
        $value = strtoupper(trim($value));
        if ($value === '') {
            return $allowEmpty ? '' : null;
        }

        $value = str_replace([' ', '\t'], '_', $value);
        if (!isset(self::PERIOD_MAP[$value])) {
            return $allowEmpty ? '' : null;
        }

        return self::PERIOD_MAP[$value];
    }

    /**
     * Parse a billing-frequency attribute value into a positive integer.
     *
     * Accepts bare integers ("1"), unit-qualified values ("1 Month", "30 Days"),
     * and period labels used as frequency on some catalogs ("Monthly", "Quarterly").
     *
     * @param string|null $inferredPeriod Set to a PERIOD_MAP value when the
     *                                    frequency string embeds a unit.
     */
    protected function parseBillingFrequency(string $raw, ?string &$inferredPeriod = null): int
    {
        if (function_exists('paypalac_parse_billing_frequency')) {
            return paypalac_parse_billing_frequency($raw, $inferredPeriod);
        }

        $raw = trim($raw);
        $inferredPeriod = null;
        if ($raw === '') {
            return 0;
        }

        if (preg_match('/^\d+$/', $raw) === 1) {
            return (int) $raw;
        }

        if (preg_match('/^(\d+)\s*(day|days|week|weeks|month|months|year|years)\b/i', $raw, $m) === 1) {
            $count = (int) $m[1];
            $unit = strtolower($m[2]);
            if (str_starts_with($unit, 'day')) {
                $inferredPeriod = 'DAY';
            } elseif (str_starts_with($unit, 'week')) {
                $inferredPeriod = 'WEEK';
            } elseif (str_starts_with($unit, 'month')) {
                $inferredPeriod = 'MONTH';
            } elseif (str_starts_with($unit, 'year')) {
                $inferredPeriod = 'YEAR';
            }
            return $count > 0 ? $count : 0;
        }

        $named = [
            'daily' => [1, 'DAY'],
            'day' => [1, 'DAY'],
            'weekly' => [1, 'WEEK'],
            'week' => [1, 'WEEK'],
            'monthly' => [1, 'MONTH'],
            'month' => [1, 'MONTH'],
            'quarterly' => [3, 'MONTH'],
            'quarter' => [3, 'MONTH'],
            'yearly' => [1, 'YEAR'],
            'annually' => [1, 'YEAR'],
            'annual' => [1, 'YEAR'],
            'year' => [1, 'YEAR'],
            'semimonthly' => [1, 'SEMI_MONTH'],
            'semimonth' => [1, 'SEMI_MONTH'],
        ];
        $key = strtolower(preg_replace('/[^a-z]/', '', $raw) ?? '');
        if (isset($named[$key])) {
            $inferredPeriod = $named[$key][1];
            return $named[$key][0];
        }

        if (preg_match('/(\d+)/', $raw, $m) === 1) {
            return (int) $m[1];
        }

        return 0;
    }

    /**
     * Parse total billing cycles; "Good until cancelled" and similar labels => 0.
     */
    protected function parseTotalBillingCycles(string $raw): int
    {
        if (function_exists('paypalac_parse_total_billing_cycles')) {
            return paypalac_parse_total_billing_cycles($raw);
        }

        $raw = trim($raw);
        if ($raw === '') {
            return 0;
        }

        $normalized = strtolower(preg_replace('/[^a-z0-9]+/', '', $raw) ?? '');
        if ($normalized === '' || str_contains($normalized, 'gooduntil') || str_contains($normalized, 'untilcancelled') || str_contains($normalized, 'indefinite') || str_contains($normalized, 'unlimited')) {
            return 0;
        }

        if (preg_match('/(\d+)/', $raw, $m) === 1) {
            return (int) $m[1];
        }

        return 0;
    }

    protected function parseAmount(string $raw): float
    {
        $raw = trim($raw);
        if ($raw === '') {
            return 0.0;
        }

        $normalized = str_replace([',', ' '], ['', ''], $raw);
        $normalized = preg_replace('/[^0-9\.-]/', '', $normalized) ?? '';

        return (float)$normalized;
    }

    /**
     * Persist PayPal vault token from session before findVaultRecord(), matching auto.paypaladvcheckout_vault.
     * Required because this observer often runs first on NOTIFY_CHECKOUT_PROCESS_AFTER_ORDER_CREATE_ADD_PRODUCTS.
     *
     * @return void
     */
    protected function ensureSessionVaultPersistedForOrder(int $ordersId, int $customersId): void
    {
        if ($ordersId <= 0 || $customersId <= 0) {
            return;
        }

        if (!isset($_SESSION['PayPalAdvancedCheckout']['VaultCardData'])) {
            return;
        }

        $vaultCardData = $_SESSION['PayPalAdvancedCheckout']['VaultCardData'];
        if (!is_array($vaultCardData) || empty($vaultCardData['card_source'])) {
            return;
        }

        $cardSource = $vaultCardData['card_source'];
        $visible = (bool)($vaultCardData['visible'] ?? false);
        $storedVault = VaultManager::saveVaultedCard($customersId, $ordersId, $cardSource, $visible);
        if ($storedVault !== null) {
            global $zco_notifier;
            if (is_object($zco_notifier) && method_exists($zco_notifier, 'notify')) {
                $zco_notifier->notify('NOTIFY_PAYPALAC_VAULT_CARD_SAVED', $storedVault);
            }
            $this->log->write('    Session VaultCardData persisted before subscription loop (observer load order).');
            unset($_SESSION['PayPalAdvancedCheckout']['VaultCardData']);
        }
    }

    /**
     * Find vault record for the specific order.
     * 
     * This method only returns vault records that were specifically created for the given order.
     * It does NOT fall back to other vault records the customer may have from previous orders,
     * as this would incorrectly associate a subscription with a different payment method
     * (e.g., using an old saved credit card when the customer paid with Google Pay).
     * 
     * @return array<string,mixed>|null
     */
    protected function findVaultRecord(int $customersId, int $ordersId): ?array
    {
        if ($customersId <= 0) {
            return null;
        }

        $records = VaultManager::getCustomerVaultedCards($customersId, false);
        if (empty($records)) {
            return null;
        }

        foreach ($records as $record) {
            if ((int)($record['orders_id'] ?? 0) === $ordersId) {
                return $record;
            }
        }

        // Fallback for saved card payments (e.g. paypalac_savedcard module):
        // When the customer pays with a previously-saved card, the vault record belongs
        // to an earlier order so it will never match $ordersId above. The payment
        // module stores the explicitly-selected vault_id in session, so we can use
        // that to find the correct vault record without risk of accidentally associating
        // a subscription with an unrelated payment instrument.
        $sessionVaultId = (string)($_SESSION['PayPalAdvancedCheckout']['saved_card'] ?? '');
        if ($sessionVaultId !== '' && $sessionVaultId !== 'new') {
            foreach ($records as $record) {
                if ((string)($record['vault_id'] ?? '') === $sessionVaultId) {
                    $this->log->write("    Found vault record via session saved_card vault_id: $sessionVaultId (originally linked to order #" . ($record['orders_id'] ?? 0) . ")");
                    return $record;
                }
            }
            $this->log->write("    Session has saved_card vault_id $sessionVaultId but no matching vault record found for customer #$customersId.");
        }

        // Final fallback for paypalac-family orders: if the customer has active vaulted
        // cards but none specifically match this order, use the most recently used active
        // vault. This is needed because the PayPal Smart Buttons flow does not always
        // populate session VaultCardData or the saved-card selector before the
        // AFTER_ORDER_CREATE_ADD_PRODUCTS notification fires (timing/UX variability),
        // which would otherwise leave the subscription row unwritten even though the
        // customer has stored payment methods we can charge against.
        //
        // We restrict this fallback to paypalac-family payment modules so that a
        // subscription is never silently linked to a vault belonging to an unrelated
        // payment instrument (e.g. a one-off card the customer entered for a different
        // order).
        if ($this->orderUsesPaypalacFamilyModule($ordersId)) {
            $bestRecord = null;
            $bestTimestamp = '';
            foreach ($records as $record) {
                $status = strtoupper((string)($record['status'] ?? ''));
                if (!in_array($status, ['VAULTED', 'ACTIVE', 'APPROVED'], true)) {
                    continue;
                }
                if ((int)($record['visible'] ?? 1) !== 1) {
                    continue;
                }
                $timestamp = (string)($record['last_used'] ?? $record['last_modified'] ?? $record['date_added'] ?? '');
                if ($bestRecord === null || strcmp($timestamp, $bestTimestamp) > 0) {
                    $bestRecord = $record;
                    $bestTimestamp = $timestamp;
                }
            }
            if ($bestRecord !== null) {
                $this->log->write(
                    "    Found vault record via paypalac-family fallback: vault #"
                    . ($bestRecord['paypal_vault_id'] ?? '?')
                    . " (most recently used active vault for customer #$customersId, originally linked to order #"
                    . ($bestRecord['orders_id'] ?? 0)
                    . ")."
                );
                return $bestRecord;
            }
        }

        // Do not fall back to arbitrary vault records when the payment module is not
        // part of the paypalac family. This guards against incorrectly associating a
        // subscription with a payment method from a different order (e.g. a Google Pay
        // token stored from a one-off purchase).
        return null;
    }

    /**
     * Determine whether the order was paid with one of the paypalac-family modules
     * (paypalac, paypalac_creditcard, paypalac_savedcard, paypalac_applepay,
     * paypalac_googlepay, paypalac_venmo, paypalac_paylater).
     */
    /**
     * Create a Zen Cart-managed (saved-card) subscription row in
     * TABLE_SAVED_CREDIT_CARDS_RECURRING for a product that carries the three
     * Zen Cart subscription attributes (Billing Period, Billing Frequency,
     * Total Billing Cycles) but no paypal_subscription_plan_id. The cron
     * paypalac_saved_card_recurring.php picks up these rows and bills the
     * customer's saved card on the configured cadence.
     *
     * Returns true when a subscription row was created, false otherwise.
     *
     * @param array<string,scalar> $productInfo
     * @param array<string,mixed> $subscriptionAttributes
     * @param array<string,scalar> $attributeMap
     * @param array<string,mixed>|null $vaultRecord
     * @param array<string,scalar> $billingAddress
     * @param array<string,scalar|null> $shippingInfo
     */
    protected function createZenCartManagedSubscription(
        int $customersId,
        int $ordersId,
        int $ordersProductsId,
        array $productInfo,
        array $subscriptionAttributes,
        array $attributeMap,
        ?array $vaultRecord,
        string $currency,
        array $billingAddress,
        array $shippingInfo
    ): bool {
        $this->log->write("    Product #$ordersProductsId: Zen Cart-managed subscription (no plan_id), routing to saved_credit_cards_recurring.");

        if (class_exists('PayPalAdvancedCheckout\\Common\\SavedCreditCardsManager')) {
            \PayPalAdvancedCheckout\Common\SavedCreditCardsManager::ensureSchema();
        }

        $savedCreditCardId = $this->getSavedCreditCardId($vaultRecord);
        if ($savedCreditCardId === 0) {
            $this->log->write("    WARNING: No saved_credit_card_id found for vault on order #$ordersId; subscription cannot be created yet. The recurring cron will pick it up once the vault completes (e.g. via NOTIFY_PAYPALAC_VAULT_CARD_SAVED) or once the order is captured.");
            return false;
        }

        $nextBillingDate = $this->calculateNextBillingDate($subscriptionAttributes);

        if (!class_exists('paypalacSavedCardRecurring')) {
            $savedCardRecurringPath = DIR_FS_CATALOG . DIR_WS_CLASSES . 'paypalacSavedCardRecurring.php';
            if (file_exists($savedCardRecurringPath)) {
                require_once $savedCardRecurringPath;
            }
        }
        if (!class_exists('paypalacSavedCardRecurring')) {
            $this->log->write("    ERROR: paypalacSavedCardRecurring class not available; legacy subscription cannot be scheduled.");
            return false;
        }

        $savedCardRecurring = new \paypalacSavedCardRecurring();
        $subscriptionId = $savedCardRecurring->schedule_payment(
            (float)$productInfo['final_price'],
            $nextBillingDate,
            $savedCreditCardId,
            $ordersProductsId,
            'Subscription created from order #' . $ordersId,
            array_merge(
                [
                    'customers_id' => $customersId,
                    'orders_id' => $ordersId,
                    'products_id' => (int)$productInfo['products_id'],
                    'products_name' => (string)$productInfo['products_name'],
                    'currency_code' => $currency,
                    'billing_period' => $subscriptionAttributes['billing_period'],
                    'billing_frequency' => $subscriptionAttributes['billing_frequency'],
                    'total_billing_cycles' => $subscriptionAttributes['total_billing_cycles'],
                    'subscription_attributes' => $attributeMap,
                ],
                $billingAddress,
                $shippingInfo
            )
        );

        if ($subscriptionId > 0) {
            $this->log->write("    SUCCESS: Saved-card subscription #$subscriptionId created for product #$ordersProductsId.");
            return true;
        }

        $this->log->write("    ERROR: Failed to create saved-card subscription for product #$ordersProductsId.");
        return false;
    }

    /**
     * Re-run subscription creation for an order whose authorization has just
     * been fully captured. This recovers the case where the recurring observer
     * could not write a saved_credit_cards_recurring row at order-create time
     * (typically because the vault token wasn't yet available, or the legacy
     * path was momentarily disabled when the order was placed) but the order
     * has now been settled.
     *
     * @param object $class
     * @param string $eventID
     * @param array<string,mixed> $payload
     */
    public function updateNotifyPaypalacAuthorizationFullyCaptured(&$class, $eventID, $payload): void
    {
        $ordersId = (int)($payload['orders_id'] ?? 0);
        if ($ordersId <= 0) {
            return;
        }

        $this->log->write("==> Subscription Observer: NOTIFY_PAYPALAC_AUTHORIZATION_FULLY_CAPTURED fired for order #$ordersId.");

        global $db;

        $orderInfo = $db->Execute(
            "SELECT customers_id, currency, currency_value,
                    billing_name, billing_company,
                    billing_street_address, billing_suburb, billing_city,
                    billing_state, billing_postcode, billing_country,
                    delivery_country
               FROM " . TABLE_ORDERS . "
              WHERE orders_id = " . $ordersId . "
              LIMIT 1"
        );

        if ($orderInfo->EOF) {
            $this->log->write("    ERROR: Order #$ordersId not found in database.");
            return;
        }

        if (function_exists('paypalac_materialize_accept_automatic_renewal_order_attributes')) {
            paypalac_materialize_accept_automatic_renewal_order_attributes($ordersId);
        }

        $customersId = (int)$orderInfo->fields['customers_id'];
        $currency = (string)($orderInfo->fields['currency'] ?? (defined('DEFAULT_CURRENCY') ? DEFAULT_CURRENCY : ''));
        $currencyValue = (float)($orderInfo->fields['currency_value'] ?? 1.0);

        $billingAddress = [
            'billing_name' => (string)($orderInfo->fields['billing_name'] ?? ''),
            'billing_company' => (string)($orderInfo->fields['billing_company'] ?? ''),
            'billing_street_address' => (string)($orderInfo->fields['billing_street_address'] ?? ''),
            'billing_suburb' => (string)($orderInfo->fields['billing_suburb'] ?? ''),
            'billing_city' => (string)($orderInfo->fields['billing_city'] ?? ''),
            'billing_state' => (string)($orderInfo->fields['billing_state'] ?? ''),
            'billing_postcode' => (string)($orderInfo->fields['billing_postcode'] ?? ''),
            'billing_country' => (string)($orderInfo->fields['billing_country'] ?? ''),
        ];

        if (!empty($billingAddress['billing_country'])) {
            $countryQuery = $db->Execute(
                "SELECT countries_id, countries_iso_code_2
                   FROM " . TABLE_COUNTRIES . "
                  WHERE countries_name = '" . zen_db_input($billingAddress['billing_country']) . "'
                  LIMIT 1"
            );
            if (!$countryQuery->EOF) {
                $billingAddress['billing_country_id'] = (int)$countryQuery->fields['countries_id'];
                $billingAddress['billing_country_code'] = (string)$countryQuery->fields['countries_iso_code_2'];
            }
        }

        $shippingInfo = ['shipping_method' => '', 'shipping_cost' => null];
        $shippingQuery = $db->Execute(
            "SELECT class, title, value
               FROM " . TABLE_ORDERS_TOTAL . "
              WHERE orders_id = " . $ordersId . "
                AND class = 'ot_shipping'
              LIMIT 1"
        );
        if (!$shippingQuery->EOF) {
            $shippingInfo['shipping_method'] = (string)$shippingQuery->fields['title'];
            $shippingInfo['shipping_cost'] = (float)$shippingQuery->fields['value'];
        }

        $vaultRecord = $this->findVaultRecord($customersId, $ordersId);
        if ($vaultRecord !== null) {
            $this->syncVaultToSavedCreditCards($vaultRecord);
        }

        $products = $db->Execute(
            "SELECT orders_products_id, products_id, products_name, products_quantity, final_price
               FROM " . TABLE_ORDERS_PRODUCTS . "
              WHERE orders_id = " . $ordersId
        );

        if ($products->EOF) {
            return;
        }

        while (!$products->EOF) {
            $ordersProductsId = (int)$products->fields['orders_products_id'];

            // If a subscription row (either saved-card or REST) already exists for
            // this orders_products_id, leave it alone. Re-running creation could
            // duplicate billing schedules.
            if ($this->subscriptionAlreadyExists($ordersProductsId)) {
                $this->log->write("    Product #$ordersProductsId already has a subscription row; skipping.");
                $products->MoveNext();
                continue;
            }

            $attributeMap = $this->getAttributeMap($ordersProductsId);
            $subscriptionAttributes = $this->extractSubscriptionAttributes($attributeMap);
            if ($subscriptionAttributes === null) {
                $products->MoveNext();
                continue;
            }

            if (!empty($subscriptionAttributes['plan_id'])) {
                // PayPal-managed subscriptions are written via the dedicated
                // checkout-time path, not here. The BILLING.SUBSCRIPTION.* webhook
                // family keeps these in sync with PayPal.
                $products->MoveNext();
                continue;
            }

            $this->createZenCartManagedSubscription(
                $customersId,
                $ordersId,
                $ordersProductsId,
                [
                    'products_id' => (int)$products->fields['products_id'],
                    'products_name' => (string)$products->fields['products_name'],
                    'final_price' => (float)$products->fields['final_price'],
                ],
                $subscriptionAttributes,
                $attributeMap,
                $vaultRecord,
                $currency,
                $billingAddress,
                $shippingInfo
            );

            $products->MoveNext();
        }
    }

    /**
     * Returns true when an active subscription row already exists for the given
     * orders_products_id in either the legacy (saved_credit_cards_recurring) or
     * the REST (paypal_subscriptions) table.
     */
    protected function subscriptionAlreadyExists(int $ordersProductsId): bool
    {
        if ($ordersProductsId <= 0) {
            return false;
        }

        global $db;

        if (defined('TABLE_SAVED_CREDIT_CARDS_RECURRING')) {
            $row = $db->Execute(
                "SELECT saved_credit_card_recurring_id FROM " . TABLE_SAVED_CREDIT_CARDS_RECURRING
                . " WHERE orders_products_id = " . $ordersProductsId
                . " LIMIT 1"
            );
            if (is_object($row) && !$row->EOF) {
                return true;
            }
        }

        if (defined('TABLE_PAYPAL_SUBSCRIPTIONS')) {
            $row = $db->Execute(
                "SELECT paypal_subscription_id FROM " . TABLE_PAYPAL_SUBSCRIPTIONS
                . " WHERE orders_products_id = " . $ordersProductsId
                . " LIMIT 1"
            );
            if (is_object($row) && !$row->EOF) {
                return true;
            }
        }

        return false;
    }

    /**
     * Persist a paypal_subscriptions row for a PayPal-managed subscription that
     * the customer just approved during checkout. We use the resolved
     * subscription_product from the session (set by
     * paypalac::resolveSubscriptionPlanForCart()) to seed the row's billing
     * metadata. The orders_products_id of the matching line item is attached
     * so the admin manager can join cleanly.
     */
    protected function logPayPalManagedSubscription(int $ordersId): void
    {
        $sessionSubscription = $_SESSION['PayPalAdvancedCheckout']['Subscription'] ?? [];
        $remoteId = (string)($sessionSubscription['id'] ?? '');
        if ($remoteId === '') {
            $this->log->write('    PayPal subscription session present but no remote id; nothing logged.');
            return;
        }

        $product = $sessionSubscription['subscription_product'] ?? [];
        $productsId = (int)($product['products_id'] ?? 0);
        if ($productsId <= 0) {
            $this->log->write('    PayPal subscription session present but no products_id; nothing logged.');
            return;
        }

        global $db;

        // Look up the matching orders_products row so we can attach the
        // orders_products_id; if absent we still log against orders_id.
        $orderProductRow = $db->Execute(
            "SELECT orders_products_id, products_name, products_quantity, final_price"
            . " FROM " . TABLE_ORDERS_PRODUCTS
            . " WHERE orders_id = " . (int)$ordersId
            . " AND products_id = " . (int)$productsId
            . " LIMIT 1"
        );

        $ordersProductsId = 0;
        $productsName = (string)($product['products_name'] ?? '');
        $productsQuantity = 1.0;
        $finalPrice = (float)($product['amount'] ?? 0);

        if (is_object($orderProductRow) && !$orderProductRow->EOF) {
            $ordersProductsId = (int)$orderProductRow->fields['orders_products_id'];
            $productsName = (string)($orderProductRow->fields['products_name'] ?? $productsName);
            $productsQuantity = (float)($orderProductRow->fields['products_quantity'] ?? $productsQuantity);
            $finalPrice = (float)($orderProductRow->fields['final_price'] ?? $finalPrice);
        }

        $orderRow = $db->Execute(
            "SELECT customers_id, currency, currency_value"
            . " FROM " . TABLE_ORDERS
            . " WHERE orders_id = " . (int)$ordersId
            . " LIMIT 1"
        );
        $customersId = is_object($orderRow) && !$orderRow->EOF ? (int)$orderRow->fields['customers_id'] : 0;
        $currencyCode = is_object($orderRow) && !$orderRow->EOF ? (string)$orderRow->fields['currency'] : (string)($product['currency_code'] ?? 'USD');
        $currencyValue = is_object($orderRow) && !$orderRow->EOF ? (float)$orderRow->fields['currency_value'] : 1.0;

        $subscriptionRecordId = SubscriptionManager::logSubscription([
            'customers_id' => $customersId,
            'orders_id' => $ordersId,
            'orders_products_id' => $ordersProductsId,
            'products_id' => $productsId,
            'products_name' => $productsName,
            'products_quantity' => $productsQuantity,
            'plan_id' => (string)($sessionSubscription['plan_id'] ?? ''),
            'paypal_subscription_remote_id' => $remoteId,
            'billing_period' => (string)($product['billing_period'] ?? ''),
            'billing_frequency' => (int)($product['billing_frequency'] ?? 0),
            'total_billing_cycles' => (int)($product['total_billing_cycles'] ?? 0),
            'trial_period' => (string)($product['trial_period'] ?? ''),
            'trial_frequency' => (int)($product['trial_frequency'] ?? 0),
            'trial_total_cycles' => (int)($product['trial_total_cycles'] ?? 0),
            'setup_fee' => (float)($product['setup_fee'] ?? 0),
            'amount' => $finalPrice > 0 ? $finalPrice : (float)($product['amount'] ?? 0),
            'currency_code' => $currencyCode,
            'currency_value' => $currencyValue,
            'paypal_vault_id' => 0,
            'vault_id' => '',
            'status' => 'pending', // BILLING.SUBSCRIPTION.ACTIVATED webhook flips this to active
        ]);

        $this->log->write(
            "    Logged PayPal-managed subscription row #$subscriptionRecordId for order #$ordersId"
            . " (remote $remoteId, plan " . ($sessionSubscription['plan_id'] ?? '?')
            . ", product $productsId)."
        );
    }

    protected function orderUsesPaypalacFamilyModule(int $ordersId): bool
    {
        if ($ordersId <= 0) {
            return false;
        }

        global $db;

        $result = $db->Execute(
            "SELECT payment_module_code"
            . " FROM " . TABLE_ORDERS
            . " WHERE orders_id = " . (int)$ordersId
            . " LIMIT 1"
        );

        if (!is_object($result) || $result->EOF) {
            return false;
        }

        $module = strtolower((string)$result->fields['payment_module_code']);
        return $module === 'paypalac' || strpos($module, 'paypalac_') === 0;
    }

    protected function normalizeAttributeKey(string $label): string
    {
        $label = strtolower($label);
        $label = preg_replace('/[^a-z0-9]+/', '_', $label) ?? $label;
        return trim($label, '_');
    }

    /**
     * @param array<string,string> $attributeMap
     */
    protected function attributeMapHasAcceptedAutomaticRenewal(array $attributeMap): bool
    {
        if (function_exists('paypalac_attribute_map_has_accepted_automatic_renewal')) {
            return paypalac_attribute_map_has_accepted_automatic_renewal($attributeMap);
        }

        foreach ($attributeMap as $key => $value) {
            $normalizedKey = preg_replace('/[^a-z0-9]/', '', strtolower((string) $key)) ?? '';
            if ($normalizedKey !== 'acceptautomaticrenewal' && $normalizedKey !== 'automaticrenewal') {
                continue;
            }

            $v = strtolower(trim((string) $value));
            if ($v !== '' && !in_array($v, ['0', 'false', 'off', 'no', 'unchecked'], true)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Get saved_credit_card_id from vault record by looking up in TABLE_SAVED_CREDIT_CARDS.
     * 
     * @param array|null $vaultRecord The vault record from VaultManager
     * @return int The saved_credit_card_id or 0 if not found
     */
    protected function getSavedCreditCardId(?array $vaultRecord): int
    {
        if ($vaultRecord === null) {
            return 0;
        }
        
        $vaultId = (string)($vaultRecord['vault_id'] ?? '');
        if ($vaultId === '') {
            return 0;
        }
        
        global $db;
        
        // Ensure saved_credit_cards table exists and has all required columns
        // This must be called unconditionally because the table constants are always defined
        // in extra_datafiles/ppac_database_tables.php, so conditional checks won't work
        if (class_exists('PayPalAdvancedCheckout\\Common\\SavedCreditCardsManager')) {
            \PayPalAdvancedCheckout\Common\SavedCreditCardsManager::ensureSchema();
        }
        
        if (!defined('TABLE_SAVED_CREDIT_CARDS')) {
            $this->log->write("    ERROR: TABLE_SAVED_CREDIT_CARDS constant not defined.");
            return 0;
        }
        
        // Use parameterized query approach - zen_db_input provides escaping
        $safeVaultId = zen_db_input($vaultId);
        $result = $db->Execute(
            "SELECT saved_credit_card_id FROM " . TABLE_SAVED_CREDIT_CARDS . "
             WHERE vault_id = '$safeVaultId'
             AND is_deleted = 0
             LIMIT 1"
        );
        
        if ($result->EOF) {
            $this->log->write("    No saved_credit_card found for vault_id: $vaultId");
            return 0;
        }
        
        return (int)$result->fields['saved_credit_card_id'];
    }

    /**
     * Calculate the next billing date based on subscription attributes.
     * 
     * @param array $subscriptionAttributes The subscription attributes
     * @return string The next billing date in Y-m-d format
     */
    protected function calculateNextBillingDate(array $subscriptionAttributes): string
    {
        // Check for a future start date in the product's order attributes.
        // If the subscription has a start date that is in the future, use it as the
        // next billing date instead of calculating from today + billing period.
        $attributeMap = $subscriptionAttributes['attributes'] ?? [];
        $startDate = $attributeMap['start_date'] ?? ($attributeMap['startdate'] ?? '');
        if ($startDate !== '') {
            $startTimestamp = strtotime($startDate);
            if ($startTimestamp !== false && $startTimestamp > strtotime('today')) {
                return date('Y-m-d', $startTimestamp);
            }
        }

        $billingPeriod = $subscriptionAttributes['billing_period'] ?? 'MONTH';
        $billingFrequency = (int)($subscriptionAttributes['billing_frequency'] ?? 1);
        
        if ($billingFrequency <= 0) {
            $billingFrequency = 1;
        }
        
        // Start from today
        $date = new DateTime();
        
        // Map PayPal period to PHP DateInterval
        switch (strtoupper($billingPeriod)) {
            case 'DAY':
                $date->modify('+' . $billingFrequency . ' days');
                break;
            case 'WEEK':
                $date->modify('+' . ($billingFrequency * 7) . ' days');
                break;
            case 'SEMI_MONTH':
                // Semi-monthly is approximately 15 days
                $date->modify('+15 days');
                break;
            case 'YEAR':
                $date->modify('+' . $billingFrequency . ' years');
                break;
            case 'MONTH':
            default:
                $date->modify('+' . $billingFrequency . ' months');
                break;
        }
        
        return $date->format('Y-m-d');
    }

    /**
     * Sync vault record to saved_credit_cards table for Zen Cart-managed subscriptions.
     * 
     * This method creates a record in TABLE_SAVED_CREDIT_CARDS based on the vault record,
     * enabling Zen Cart-managed subscriptions to reference the saved card via saved_credit_card_id.
     * If a record with the same vault_id already exists, no action is taken.
     * 
     * @param array $vaultRecord The vault record from VaultManager
     */
    protected function syncVaultToSavedCreditCards(array $vaultRecord): void
    {
        global $db;
        
        // Ensure saved_credit_cards table exists and has all required columns
        // This must be called unconditionally because the table constants are always defined
        // in extra_datafiles/ppac_database_tables.php, so conditional checks won't work
        if (class_exists('PayPalAdvancedCheckout\\Common\\SavedCreditCardsManager')) {
            \PayPalAdvancedCheckout\Common\SavedCreditCardsManager::ensureSchema();
        }
        
        if (!defined('TABLE_SAVED_CREDIT_CARDS')) {
            $this->log->write("    ERROR: TABLE_SAVED_CREDIT_CARDS constant not defined, cannot sync vault to saved cards.");
            return;
        }
        
        $vaultId = (string)($vaultRecord['vault_id'] ?? '');
        if ($vaultId === '') {
            $this->log->write("    WARNING: Cannot sync vault to saved cards - vault_id is empty.");
            return;
        }

        if ((int)($vaultRecord['visible'] ?? 0) !== 1) {
            $this->log->write("    Skipping saved_credit_cards sync for backend-only vault token: $vaultId");
            return;
        }
        
        // Check if an active (non-deleted) record already exists for this vault_id.
        // The is_deleted=0 filter must match getSavedCreditCardId() so that both methods
        // agree on whether a usable record exists. Without this, a soft-deleted record
        // would cause syncVault to skip creation while getSavedCreditCardId returns 0.
        $safeVaultId = zen_db_input($vaultId);
        $existing = $db->Execute(
            "SELECT saved_credit_card_id, is_deleted FROM " . TABLE_SAVED_CREDIT_CARDS . "
             WHERE vault_id = '$safeVaultId'
             LIMIT 1"
        );
        
        if (!$existing->EOF) {
            $existingId = (int)$existing->fields['saved_credit_card_id'];
            $isDeleted = (int)($existing->fields['is_deleted'] ?? 0);
            
            if ($isDeleted === 0) {
                $this->log->write("    Saved credit card record already exists for vault_id: $vaultId (ID: $existingId)");
                return;
            }
            
            // Record exists but is soft-deleted. Reactivate it so getSavedCreditCardId can find it.
            $this->log->write("    Reactivating soft-deleted saved credit card #$existingId for vault_id: $vaultId");
            $now = date('Y-m-d H:i:s');
            $db->Execute(
                "UPDATE " . TABLE_SAVED_CREDIT_CARDS . "
                 SET is_deleted = 0, last_modified = '$now'
                 WHERE saved_credit_card_id = $existingId"
            );
            return;
        }
        
        // Extract card data from vault record
        $customersId = (int)($vaultRecord['customers_id'] ?? 0);
        
        if ($customersId <= 0) {
            $this->log->write("    WARNING: Cannot sync vault to saved cards - customers_id is invalid.");
            return;
        }
        
        $cardType = (string)($vaultRecord['brand'] ?? $vaultRecord['card_type'] ?? '');
        $lastDigits = (string)($vaultRecord['last_digits'] ?? '');
        $expiry = (string)($vaultRecord['expiry'] ?? ''); // Format: YYYY-MM
        $holderName = (string)($vaultRecord['cardholder_name'] ?? '');
        
        // Parse expiry into month and year
        $expiryMonth = '';
        $expiryYear = '';
        if ($expiry !== '' && preg_match('/^(\d{4})-(\d{2})$/', $expiry, $matches)) {
            $expiryYear = $matches[1];
            $expiryMonth = $matches[2];
        }
        
        // Build the INSERT dynamically to include legacy columns if they exist.
        // The legacy saved_credit_cards table (created by installer 1_0_0.php) has
        // NOT NULL columns without DEFAULT values (name_on_card, paypal_transaction_id,
        // is_primary). Omitting these from the INSERT causes a failure in MySQL strict mode.
        // ensureSchema() sets DEFAULT values on these columns, but we also include them
        // explicitly as a safety net in case ensureSchema hasn't run yet for this request.
        $now = date('Y-m-d H:i:s');
        $safeCustomersId = (int)$customersId;
        $safeType = zen_db_input($cardType);
        $safeLastDigits = zen_db_input($lastDigits);
        $safeExpiryMonth = zen_db_input($expiryMonth);
        $safeExpiryYear = zen_db_input($expiryYear);
        $safeHolderName = zen_db_input($holderName);
        
        $columns = 'customers_id, type, last_digits, expiry_month, expiry_year, holder_name, '
                 . 'billing_address_id, is_default, is_deleted, vault_id, date_added, last_modified';
        $values = "$safeCustomersId, '$safeType', '$safeLastDigits', '$safeExpiryMonth', '$safeExpiryYear', "
                . "'$safeHolderName', 0, 0, 0, '$safeVaultId', '$now', '$now'";
        
        // Include legacy columns if they exist in the table to avoid strict mode errors
        $legacyColumns = [
            'name_on_card' => "'" . zen_db_input($holderName) . "'",
            'paypal_transaction_id' => "''",
            'is_primary' => "0",
        ];
        foreach ($legacyColumns as $col => $val) {
            $check = $db->Execute(
                "SHOW COLUMNS FROM " . TABLE_SAVED_CREDIT_CARDS . " LIKE '$col'"
            );
            if ($check instanceof \queryFactoryResult && $check->RecordCount() > 0) {
                $columns .= ", $col";
                $values .= ", $val";
            }
        }
        
        $db->Execute(
            "INSERT INTO " . TABLE_SAVED_CREDIT_CARDS . " ($columns) VALUES ($values)"
        );
        
        $savedCreditCardId = $db->Insert_ID();
        $this->log->write("    SUCCESS: Created saved_credit_card record #$savedCreditCardId for vault_id: $vaultId");
    }

    /**
     * True when PayPal Advanced Checkout is configured for authorize (not final capture) on checkout.
     */
    protected function paypalacCheckoutUsesAuthorizeIntent(): bool
    {
        return defined('MODULE_PAYMENT_PAYPALAC_TRANSACTION_MODE')
            && MODULE_PAYMENT_PAYPALAC_TRANSACTION_MODE !== 'Final Sale';
    }
}
